const countryRoutes = require("../modules/country/country.routes");
const stateRoutes = require("../modules/state/state.routes");
const authRoutes = require("../modules/auth/auth.routes");
const userRoutes = require("../modules/user/user.routes");
const agentReferralPartnerRoutes = require("../modules/agent-referral-partner/agent-referral-partner.routes");
const userGroupRoutes = require("../modules/user-group/user-group.routes");
const builderRoutes = require("../modules/builder/builder.routes");
const contractorRoutes = require("../modules/contractor/contractor.routes");
const serviceRoutes = require("../modules/service/service.routes");
const leadSourceRoutes = require("../modules/lead-source/lead-source.routes");
const leadRoutes = require("../modules/lead/leads.routes");
const leadsContactMapRoutes = require("../modules/leads-contact/leads-contact-map.routes");
const opportunitiesRoutes = require("../modules/opportunities/opportunities.routes");
const masterPriceListCategoryRoutes = require("../modules/master-price-category/master-price-list-category.routes");
const rangeRoutes = require("../modules/range/range.routes");
const dwellingTypeRoutes = require("../modules/dwelling-type/dwelling-type.routes");
const floorPlanRoutes = require("../modules/floor-plan/floor-plan.routes");
const floorPlanPricelistItemMapRoutes = require("../modules/floor-plan-pricelist-item-map/floor-plan-pricelist-item-map.routes");
const floorPlanFacadeMapRoutes = require("../modules/floor-plan-facade-map/floor-plan-facade-map.routes");
const masterFacadeRoutes = require("../modules/facade/master-facade.routes");
const masterPriceListCategoryItemRoutes = require("../modules/category-item/master-price-list-category-item.routes");
const conditionRoutes = require("../modules/condition/condition.routes");
const packageRoutes = require("../modules/package/package.routes");
const inclusionPackageRoutes = require("../modules/inclusion-package/inclusion-package.routes");
const propertyRoutes = require("../modules/property/property.routes");
const dashboardRoutes = require("../modules/dashboard/dashboard.routes");
const quotationRoutes = require("../modules/quotation/quotation.routes");
const jobRoutes = require("../modules/job/job.routes");
const actionsRoutes = require("../modules/actions/actions.routes");
const tagsRoutes = require("../modules/tags/tags.routes");
const workflowProcessRoutes = require("../modules/workflow-process/workflow-process.routes");
const colorRoutes = require("../modules/color/color.routes");
const colorCategoryRoutes = require("../modules/color-category/color-category.routes");
const colorSubCategoryRoutes = require("../modules/color-sub-category/color-sub-category.routes");
const colorItemRoutes = require("../modules/color-item/color-item.routes");
const colorItemCustomFieldRoutes = require("../modules/color-item-custom-field/color-item-custom-field.routes");
const colorTypeRoutes = require("../modules/color-type/color-type.routes");
const workflowProcessTaskRoutes = require("../modules/workflow-process-task/workflow-process-task.routes");
const invoiceRoutes = require("../modules/invoice/invoice.routes");
const screenRoutes = require("../modules/screen/screen.routes");
const addressRoutes = require("../modules/address/address.routes");
const companyRoutes = require("../modules/company/company.routes");
const functionalityRoutes = require("../modules/functionality/functionality.routes");
const checklistRoutes = require("../modules/checklist/checklist.routes");
const checklistItemRoutes = require("../modules/checklist-item/checklist-item.routes");
const generalSettingRoutes = require("../modules/general-setting/general-setting.routes");
const surveyorRoutes = require("../modules/surveyor/surveyor.routes");
const customFieldModuleRoutes = require("../modules/custom-field-module/custom-field-module.routes");
const customFieldRoutes = require("../modules/custom-field/custom-field.routes");
const customFieldValueRoutes = require("../modules/custom-field-value/custom-field-value.routes");
const noteTagRoutes = require("../modules/note-tag/note-tag.routes");
const roleRoutes = require("../modules/role/role.routes");
const rolePermissionRoutes = require("../modules/role-permission/role-permission.routes");
const passwordPolicyRoutes = require("../modules/password-policy/password-policy.routes");
const userRoleMappingRoutes = require("../modules/user-role-mapping/user-role-mapping.routes");
const userPasswordHistoryRoutes = require("../modules/user-password-history/user-password-history.routes");
const salesModuleSettingRoutes = require("../modules/sales-module-setting/sales-module-setting.routes");
const salesProcessRoutes = require("../modules/sales-proccess/sales-process.routes");
const salesProcessStageFunctionalityRoutes = require("../modules/sales-proccess-stage-functionality/sales-process-stage-functionality.routes");
const salesStageRoutes = require("../modules/sales-stage/sales-stage.routes");
const leadLostReasonRoutes = require("../modules/lead-lost-reason/lead-lost-reason.routes");
const clientTypeRoutes = require("../modules/client-type/client-type.routes");
const houseLandPackageSettingRoutes = require("../modules/house-land-package-setting/house-land-package-setting.routes");
const jobSettingRoutes = require("../modules/job-setting/job.setting.routes");
const jobColorSettingRoutes = require("../modules/job-color-setting/job-color-setting.routes");
const jobColorColumnRoutes = require("../modules/job-color-column/job-color-column.routes");
const jobColorColumnSectionRoutes = require("../modules/job-color-column-section/job-color-column-section.routes");
const jobWorkflowSettingRoutes = require("../modules/job-workflow-setting/job-workflow-setting.routes");
const jobInvoiceSettingRoutes = require("../modules/job-invoice-setting/job-invoice-setting.routes");
const jobInvoiceStagePaymentRoutes = require("../modules/job-invoice-stage-payment/job-invoice-stage-payment.routes");
const jobVariationSettingRoutes = require("../modules/job-variation-setting/job-variation-setting.routes");
const jobCommissionsettingRoutes = require("../modules/job-commission-setting/job-commission-setting.routes");
const jobCommissionRoutes = require("../modules/job-commission/job-commission.routes");
const jobCommissionSubStageRoutes = require("../modules/job-commission-sub-stage/job-commission-sub-stage.routes");
const jobProcessRoutes = require("../modules/job-process/job-process.routes");
const jobProcessStageFunctionalityRoutes = require("../modules/job-process-stage-functionality/job-process-stage-functionality.routes");
const jobVariationApprovalRoutes = require("../modules/job-variation-approval/job-variation-approval.routes");
const maintenanceSettingRoutes = require("../modules/maintenance-setting/maintenance-setting.routes");
const maintenanceAreaRoutes = require("../modules/maintenance-area/maintenance-area.routes");
const documentCommonFolderRoutes = require("../modules/document-common-folder/document-common-folder.routes");
const documentCommonSubfolderRoutes = require("../modules/document-common-subfolder/document-common-subfolder.routes");
const documentFileNamingRuleRoutes = require("../modules/document-file-naming-rule/document-file-naming-rule.routes");
const documentFolderMappingroutes = require("../modules/document-folder-mapping/document-folder-mapping.routes");
const integrationSettingRoutes = require("../modules/integration-setting/integration-setting.routes");
const integrationCustomFieldHeaderRoutes = require("../modules/integration-custom-field-header/integration-custom-field-header.routes");
const templateEmailRoutes = require("../modules/template-email/template-email.routes");
const integrationCustomFieldItemRoutes = require("../modules/integration-custom-field-item/integration-custom-field-item.routes");
const templateEmailSignatureRoutes = require("../modules/template-email-signature/template-email.signature.routes");
const templateNoteRoutes = require("../modules/template-note/template-note.routes");
const templatePDFRoutes = require("../modules/template-pdf/template-pdf.routes");
const schedulerEmailRoutes = require("../modules/scheduler.email/scheduler.email.routes");
const schedulerSettingRoutes = require("../modules/scheduler-setting/scheduler-setting.routes");
const portalSettingRoutes = require("../modules/portal-setting/portal-setting.routes");
const priceListRoutes = require("../modules/price-list/price-list.routes");
const priceListItemRoutes = require("../modules/price-list-item/price-list-item.routes");
const priceListItemConditionRoutes = require("../modules/price-list-item-condition/price-list-item-condition.routes");
const supplierTypeRoutes = require("../modules/supplier-type/supplier-type.route");
const supplierRoutes = require("../modules/supplier/supplier.routes");
const supplierTypeMapRoutes = require("../modules/supplier-supplier-type-map/supplier-supplier-type-map.routes");
const supplierContactRoutes = require("../modules/supplier-contact/supplier-contact.routes");
const supplierDocumentRoutes = require("../modules/supplier-document/supplier-document.routes");
const surveyTemplateRoutes = require("../modules/survey-template/survey-template.routes");
const surveyTemplateQuestionRoutes = require("../modules/survey-template-question/survey-template-question.routes");
const packageGroupRoutes = require("../modules/package-group/package-group.routes");
const packagePriceListItemMapRoutes = require("../modules/package-pricelist-item-map/package-pricelist-item-map.routes");
const taskRoutes = require("../modules/task/task.routes");
const locationRoutes = require("../modules/location/location.routes");
const estateRoutes = require("../modules/estate/estate.routes");
const estateFeatureRoutes = require("../modules/estate-feature/estate-feature.routes");
const estateStageRoutes = require("../modules/estate-stage/estate-stage.routes");
const estateDocumentImageRoutes = require("../modules/estate-document-image/estate-document-image.routes");
const constructionSettingRoutes = require("../modules/construction-setting/construction-setting.routes");
const constructionOptionRoutes = require("../modules/construction-option/construction-option.routes");
const quotationSettingRoutes = require("../modules/quotation-setting/quotation-setting.routes");
const appointmentRoutes = require("../modules/appointment/appointment.routes");
const holidayRoutes = require("../modules/holiday/holiday.routes");
const recalculateDateRoutes = require("../modules/recalculate-date/recalculate-date.routes");
const constructionTypeRoutes = require("../modules/construction-type/construction-type.routes");
const constructionStageRoutes = require("../modules/construction-stage/construction-stage-.routes");
const constructionChecklistRoutes = require("../modules/construction-checklist/construction-checklist.routes");
const constructionSubChecklistRoutes = require("../modules/construction-sub-checklist/construction-sub-checklist.routes");
const constructionChecklistPredecessorRoutes = require("../modules/construction-checklist-predecessor/construction-checklist-predecessor.routes");
const constructionInspectionChecklistRoutes = require("../modules/construction-inspection-checklist/construction-inspection-checklist.routes");
const constructionOHSRoutes = require("../modules/construction-ohs/construction-ohs.routes");
const constructionEtsRechargeRoutes = require("../modules/construction-ets-recharge/construction-ets-recharge.routes");
const constructionEtsRechargeApprovalRoutes = require("../modules/construction-ets-recharge-approval/construction-ets-recharge-approval.routes");
const timezoneRoutes = require("../modules/timezone/timezone.routes");
const roleTypeRoutes = require("../modules/role-type/role-type.routes");
const costCenterRoutes = require("../modules/cost-center/cost-center.routes");
const complianceTypeRoutes = require("../modules/compliance-type/compliance-type.routes");
const driveRoutes = require("../modules/drive/drive.routes");
const colorGrouprouts = require("../modules/color-group/color-group.routes");
const colorGroupItemMapRoutes = require("../modules/color-group-item-map/color-group-item-map.routes");
const contractFormatRoutes = require("../modules/contract-format/contract-format.routes");
const contractSectionRoutes = require("../modules/contract-section/contract-section.routes");
const quotationFormatMasterSectionRoutes = require("../modules/quotation-format-master-section/quotation-format-master-section.routes");
const contactRoutes = require("../modules/contact/contact.routes");
const lotRoutes = require("../modules/lot/lot.routes");
const lotPackageGroupRoutes = require("../modules/lot-package-group/lot-package-group.routes");
const lotPackageRoutes = require("../modules/lot-package/lot-package.routes");
const houseFeatureRoutes = require("../modules/house-feature/house-feature.routes");
const houseLandPackageRoutes = require("../modules/house-land-package/house-land-package.routes");
const hLPackagePricelistItemCommissionRoutes = require("../modules/h-l-package-pricelist-item-commission/h-l-package-pricelist-item-commission.routes");
const jobFormRoutes = require("../modules/job-form/job-form.routes");
const businessContactRoutes = require("../modules/business-contact/business-contact.routes");
const hlPackageLotPackageMapRoutes = require("../modules/hl-package-lot-package-map/hl-package-lot-package-map.routes");
const quotationVersionCustomSectionRoutes = require("../modules/quotation-version-custom-section/quotation-version-custom-section.routes");
const quotationVersionPricelistItemMapRoutes = require("../modules/quotation-version-price-list/quotation-version-pricelist-item-map.routes");

module.exports = function (app) {
  app.use("/country", countryRoutes);
  app.use("/state", stateRoutes);
  app.use("/auth", authRoutes);
  app.use("/user", userRoutes);
  app.use("/agent-referral-partner", agentReferralPartnerRoutes);
  app.use("/user-group", userGroupRoutes);
  app.use("/builder", builderRoutes);
  app.use("/contractor", contractorRoutes);
  app.use("/service", serviceRoutes);
  app.use("/sales/lead-source", leadSourceRoutes);
  app.use("/leads", leadRoutes);
  app.use("/leads-contact-map", leadsContactMapRoutes);
  app.use("/opportunities", opportunitiesRoutes);
  app.use("/master-price-category", masterPriceListCategoryRoutes);
  app.use("/range", rangeRoutes);
  app.use("/dwelling-type", dwellingTypeRoutes);
  app.use("/floor-plan", floorPlanRoutes);
  app.use("/floor-plan-pricelist-item-map", floorPlanPricelistItemMapRoutes);
  app.use("/floor-plan-facade-map", floorPlanFacadeMapRoutes);
  app.use("/facade", masterFacadeRoutes);
  app.use("/condition", conditionRoutes);
  app.use("/category-item", masterPriceListCategoryItemRoutes);
  app.use("/package", packageRoutes);
  app.use("/inclusion-package", inclusionPackageRoutes);
  app.use("/property", propertyRoutes);
  app.use("/dashboard", dashboardRoutes);
  app.use("/quotation", quotationRoutes);
  app.use("/job", jobRoutes);
  app.use("/actions", actionsRoutes);
  app.use("/tags", tagsRoutes);
  app.use("/workflow-process", workflowProcessRoutes);
  app.use("/color", colorRoutes);
  app.use("/color-category", colorCategoryRoutes);
  app.use("/color-sub-category", colorSubCategoryRoutes);
  app.use("/color-item", colorItemRoutes);
  app.use("/color-item-custom-field", colorItemCustomFieldRoutes);
  app.use("/color-group-item-map", colorGroupItemMapRoutes);
  app.use("/color-type", colorTypeRoutes);
  app.use("/workflow-process-task", workflowProcessTaskRoutes);
  app.use("/invoice", invoiceRoutes);
  app.use("/screen", screenRoutes);
  app.use("/address", addressRoutes);
  app.use("/company", companyRoutes);
  app.use("/functionality", functionalityRoutes);
  app.use("/checklist", checklistRoutes);
  app.use("/checklist-item", checklistItemRoutes);
  app.use("/general-setting", generalSettingRoutes);
  app.use("/surveyor", surveyorRoutes);
  app.use("/custom-field-module", customFieldModuleRoutes);
  app.use("/custom-field", customFieldRoutes);
  app.use("/custom-field-value", customFieldValueRoutes);
  app.use("/note-tag", noteTagRoutes);
  app.use("/role", roleRoutes);
  app.use("/role-permission", rolePermissionRoutes);
  app.use("/password-policy", passwordPolicyRoutes);
  app.use("/user-role-mapping", userRoleMappingRoutes);
  app.use("/user-password-history", userPasswordHistoryRoutes);
  app.use("/sales-module-setting", salesModuleSettingRoutes);
  app.use("/sales-proccess", salesProcessRoutes);
  app.use(
    "/sales-proccess-stage-functionality",
    salesProcessStageFunctionalityRoutes,
  );
  app.use("/sales-stage", salesStageRoutes);
  app.use("/lead-lost-reason", leadLostReasonRoutes);
  app.use("/client-type", clientTypeRoutes);
  app.use("/house-land-package-setting", houseLandPackageSettingRoutes);
  app.use("/job-setting", jobSettingRoutes);
  app.use("/job-color-setting", jobColorSettingRoutes);
  app.use("/job-color-column", jobColorColumnRoutes);
  app.use("/job-color-column-section", jobColorColumnSectionRoutes);
  app.use("/job-workflow-setting", jobWorkflowSettingRoutes);
  app.use("/job-invoice-setting", jobInvoiceSettingRoutes);
  app.use("/job-invoice-stage-payment", jobInvoiceStagePaymentRoutes);
  app.use("/job-variation-setting", jobVariationSettingRoutes);
  app.use("/job-commission-setting", jobCommissionsettingRoutes);
  app.use("/job-commission", jobCommissionRoutes);
  app.use("/job-commission-sub-stage", jobCommissionSubStageRoutes);
  app.use("/job-process", jobProcessRoutes);
  app.use(
    "/job-process-stage-functionality",
    jobProcessStageFunctionalityRoutes,
  );
  app.use("/job-variation-approval", jobVariationApprovalRoutes);
  app.use("/maintenance-setting", maintenanceSettingRoutes);
  app.use("/maintenance-area", maintenanceAreaRoutes);
  app.use("/document-common-folder", documentCommonFolderRoutes);
  app.use("/document-common-subfolder", documentCommonSubfolderRoutes);
  app.use("/document-file-naming-rule", documentFileNamingRuleRoutes);
  app.use("/document-folder-mapping", documentFolderMappingroutes);
  app.use("/integration-setting", integrationSettingRoutes);
  app.use(
    "/integration-custom-field-header",
    integrationCustomFieldHeaderRoutes,
  );
  app.use("/integration-custom-field-item", integrationCustomFieldItemRoutes);
  app.use("/template-email", templateEmailRoutes);
  app.use("/template-email-signature", templateEmailSignatureRoutes);
  app.use("/template-note", templateNoteRoutes);
  app.use("/template-pdf", templatePDFRoutes);
  app.use("/scheduler-email", schedulerEmailRoutes);
  app.use("/scheduler-setting", schedulerSettingRoutes);
  app.use("/portal-setting", portalSettingRoutes);
  app.use("/price-list", priceListRoutes);
  app.use("/price-list-item", priceListItemRoutes);
  app.use("/price-list-item-condition", priceListItemConditionRoutes);
  app.use("/supplier-type", supplierTypeRoutes);
  app.use("/supplier", supplierRoutes);
  app.use("/supplier-type-map", supplierTypeMapRoutes);
  app.use("/supplier-contact", supplierContactRoutes);
  app.use("/supplier-document", supplierDocumentRoutes);
  app.use("/survey-template", surveyTemplateRoutes);
  app.use("/survey-template-question", surveyTemplateQuestionRoutes);
  app.use("/package-group", packageGroupRoutes);
  app.use("/package-price-list-item-map", packagePriceListItemMapRoutes);
  app.use("/task", taskRoutes);
  app.use("/location", locationRoutes);
  app.use("/estate", estateRoutes);
  app.use("/estate-feature", estateFeatureRoutes);
  app.use("/estate-stage", estateStageRoutes);
  app.use("/estate-document-image", estateDocumentImageRoutes);
  app.use("/construction-setting", constructionSettingRoutes);
  app.use("/construction-option", constructionOptionRoutes);
  app.use("/quotation-setting", quotationSettingRoutes);
  app.use("/appointment", appointmentRoutes);
  app.use("/holiday", holidayRoutes);
  app.use("/recalculate-date", recalculateDateRoutes);
  app.use("/construction-type", constructionTypeRoutes);
  app.use("/construction-stage", constructionStageRoutes);
  app.use("/construction-checklist", constructionChecklistRoutes);
  app.use("/construction-sub-checklist", constructionSubChecklistRoutes);
  app.use(
    "/construction-checklist-predecessor",
    constructionChecklistPredecessorRoutes,
  );
  app.use("/construction-ohs", constructionOHSRoutes);
  app.use(
    "/construction-inspection-checklist",
    constructionInspectionChecklistRoutes,
  );
  app.use("/construction-ets-recharge", constructionEtsRechargeRoutes);
  app.use(
    "/construction-ets-recharge-approval",
    constructionEtsRechargeApprovalRoutes,
  );
  app.use("/timezone", timezoneRoutes);
  app.use("/role-type", roleTypeRoutes);
  app.use("/cost-center", costCenterRoutes);
  app.use("/compliance-type", complianceTypeRoutes);
  app.use("/drive", driveRoutes);
  app.use("/color-group", colorGrouprouts);
  app.use("/contract-format", contractFormatRoutes);
  app.use("/contract-section", contractSectionRoutes);
  app.use("/quotation-format", quotationFormatMasterSectionRoutes);
  app.use("/contact", contactRoutes);
  app.use("/lot", lotRoutes);
  app.use("/lot-package-group", lotPackageGroupRoutes);
  app.use("/lot-package", lotPackageRoutes);
  app.use("/house-feature", houseFeatureRoutes);
  app.use("/house-land-package", houseLandPackageRoutes);
  app.use("/hl-package-pricelist-item-commission", hLPackagePricelistItemCommissionRoutes);
  app.use("/job-form", jobFormRoutes);
  app.use("/business-contact", businessContactRoutes);
  app.use("/hl-package-lot-package-map", hlPackageLotPackageMapRoutes);
  app.use("/quotation-version-custom-section", quotationVersionCustomSectionRoutes);
  app.use("/quotation-version-pricelist-item-map", quotationVersionPricelistItemMapRoutes);
};
