import countryRoutes from "../modules/country/country.routes.js";
import stateRoutes from "../modules/state/state.routes.js";
import authRoutes from "../modules/auth/auth.routes.js";
import userRoutes from "../modules/user/user.routes.js";
import agentReferralPartnerRoutes from "../modules/agent-referral-partner/agent-referral-partner.routes.js";
import userGroupRoutes from "../modules/user-group/user-group.routes.js";
import builderRoutes from "../modules/builder/builder.routes.js";
import contractorRoutes from "../modules/contractor/contractor.routes.js";
import serviceRoutes from "../modules/service/service.routes.js";
import leadSourceRoutes from "../modules/lead-source/lead-source.routes.js";
import leadRoutes from "../modules/lead/leads.routes.js";
import leadsContactMapRoutes from "../modules/leads-contact/leads-contact-map.routes.js";
import opportunitiesRoutes from "../modules/opportunities/opportunities.routes.js";
import masterPriceListCategoryRoutes from "../modules/master-price-category/master-price-list-category.routes.js";
import rangeRoutes from "../modules/range/range.routes.js";
import dwellingTypeRoutes from "../modules/dwelling-type/dwelling-type.routes.js";
import floorPlanRoutes from "../modules/floor-plan/floor-plan.routes.js";
import floorPlanPricelistItemMapRoutes from "../modules/floor-plan-pricelist-item-map/floor-plan-pricelist-item-map.routes.js";
import floorPlanFacadeMapRoutes from "../modules/floor-plan-facade-map/floor-plan-facade-map.routes.js";
import masterFacadeRoutes from "../modules/facade/master-facade.routes.js";
import masterPriceListCategoryItemRoutes from "../modules/category-item/master-price-list-category-item.routes.js";
import conditionRoutes from "../modules/condition/condition.routes.js";
import packageRoutes from "../modules/package/package.routes.js";
import inclusionPackageRoutes from "../modules/inclusion-package/inclusion-package.routes.js";
import propertyRoutes from "../modules/property/property.routes.js";
import dashboardRoutes from "../modules/dashboard/dashboard.routes.js";
import quotationRoutes from "../modules/quotation/quotation.routes.js";
import jobRoutes from "../modules/job/job.routes.js";
import actionsRoutes from "../modules/actions/actions.routes.js";
import tagsRoutes from "../modules/tags/tags.routes.js";
import workflowProcessRoutes from "../modules/workflow-process/workflow-process.routes.js";
import colorRoutes from "../modules/color/color.routes.js";
import colorCategoryRoutes from "../modules/color-category/color-category.routes.js";
import colorSubCategoryRoutes from "../modules/color-sub-category/color-sub-category.routes.js";
import colorItemRoutes from "../modules/color-item/color-item.routes.js";
import colorItemCustomFieldRoutes from "../modules/color-item-custom-field/color-item-custom-field.routes.js";
import colorTypeRoutes from "../modules/color-type/color-type.routes.js";
import workflowProcessTaskRoutes from "../modules/workflow-process-task/workflow-process-task.routes.js";
import invoiceRoutes from "../modules/invoice/invoice.routes.js";
import screenRoutes from "../modules/screen/screen.routes.js";
import addressRoutes from "../modules/address/address.routes.js";
import companyRoutes from "../modules/company/company.routes.js";
import functionalityRoutes from "../modules/functionality/functionality.routes.js";
import checklistRoutes from "../modules/checklist/checklist.routes.js";
import checklistItemRoutes from "../modules/checklist-item/checklist-item.routes.js";
import generalSettingRoutes from "../modules/general-setting/general-setting.routes.js";
import surveyorRoutes from "../modules/surveyor/surveyor.routes.js";
import customFieldModuleRoutes from "../modules/custom-field-module/custom-field-module.routes.js";
import customFieldRoutes from "../modules/custom-field/custom-field.routes.js";
import customFieldValueRoutes from "../modules/custom-field-value/custom-field-value.routes.js";
import noteTagRoutes from "../modules/note-tag/note-tag.routes.js";
import roleRoutes from "../modules/role/role.routes.js";
import rolePermissionRoutes from "../modules/role-permission/role-permission.routes.js";
import passwordPolicyRoutes from "../modules/password-policy/password-policy.routes.js";
import userRoleMappingRoutes from "../modules/user-role-mapping/user-role-mapping.routes.js";
import userPasswordHistoryRoutes from "../modules/user-password-history/user-password-history.routes.js";
import salesModuleSettingRoutes from "../modules/sales-module-setting/sales-module-setting.routes.js";
import salesProcessRoutes from "../modules/sales-proccess/sales-process.routes.js";
import salesProcessStageFunctionalityRoutes from "../modules/sales-proccess-stage-functionality/sales-process-stage-functionality.routes.js";
import salesStageRoutes from "../modules/sales-stage/sales-stage.routes.js";
import leadLostReasonRoutes from "../modules/lead-lost-reason/lead-lost-reason.routes.js";
import clientTypeRoutes from "../modules/client-type/client-type.routes.js";
import houseLandPackageSettingRoutes from "../modules/house-land-package-setting/house-land-package-setting.routes.js";
import jobSettingRoutes from "../modules/job-setting/job.setting.routes.js";
import jobColorSettingRoutes from "../modules/job-color-setting/job-color-setting.routes.js";
import jobColorColumnRoutes from "../modules/job-color-column/job-color-column.routes.js";
import jobColorColumnSectionRoutes from "../modules/job-color-column-section/job-color-column-section.routes.js";
import jobWorkflowSettingRoutes from "../modules/job-workflow-setting/job-workflow-setting.routes.js";
import jobInvoiceSettingRoutes from "../modules/job-invoice-setting/job-invoice-setting.routes.js";
import jobInvoiceStagePaymentRoutes from "../modules/job-invoice-stage-payment/job-invoice-stage-payment.routes.js";
import jobVariationSettingRoutes from "../modules/job-variation-setting/job-variation-setting.routes.js";
import jobCommissionsettingRoutes from "../modules/job-commission-setting/job-commission-setting.routes.js";
import jobCommissionRoutes from "../modules/job-commission/job-commission.routes.js";
import jobCommissionSubStageRoutes from "../modules/job-commission-sub-stage/job-commission-sub-stage.routes.js";
import jobProcessRoutes from "../modules/job-process/job-process.routes.js";
import jobProcessStageFunctionalityRoutes from "../modules/job-process-stage-functionality/job-process-stage-functionality.routes.js";
import jobVariationApprovalRoutes from "../modules/job-variation-approval/job-variation-approval.routes.js";
import maintenanceSettingRoutes from "../modules/maintenance-setting/maintenance-setting.routes.js";
import maintenanceAreaRoutes from "../modules/maintenance-area/maintenance-area.routes.js";
import documentCommonFolderRoutes from "../modules/document-common-folder/document-common-folder.routes.js";
import documentCommonSubfolderRoutes from "../modules/document-common-subfolder/document-common-subfolder.routes.js";
import documentFileNamingRuleRoutes from "../modules/document-file-naming-rule/document-file-naming-rule.routes.js";
import documentFolderMappingroutes from "../modules/document-folder-mapping/document-folder-mapping.routes.js";
import integrationSettingRoutes from "../modules/integration-setting/integration-setting.routes.js";
import integrationCustomFieldHeaderRoutes from "../modules/integration-custom-field-header/integration-custom-field-header.routes.js";
import templateEmailRoutes from "../modules/template-email/template-email.routes.js";
import integrationCustomFieldItemRoutes from "../modules/integration-custom-field-item/integration-custom-field-item.routes.js";
import templateEmailSignatureRoutes from "../modules/template-email-signature/template-email.signature.routes.js";
import templateNoteRoutes from "../modules/template-note/template-note.routes.js";
import templatePDFRoutes from "../modules/template-pdf/template-pdf.routes.js";
import schedulerEmailRoutes from "../modules/scheduler.email/scheduler.email.routes.js";
import schedulerSettingRoutes from "../modules/scheduler-setting/scheduler-setting.routes.js";
import portalSettingRoutes from "../modules/portal-setting/portal-setting.routes.js";
import priceListRoutes from "../modules/price-list/price-list.routes.js";
import priceListItemRoutes from "../modules/price-list-item/price-list-item.routes.js";
import priceListItemConditionRoutes from "../modules/price-list-item-condition/price-list-item-condition.routes.js";
import supplierTypeRoutes from "../modules/supplier-type/supplier-type.route.js";
import supplierRoutes from "../modules/supplier/supplier.routes.js";
import supplierTypeMapRoutes from "../modules/supplier-supplier-type-map/supplier-supplier-type-map.routes.js";
import supplierContactRoutes from "../modules/supplier-contact/supplier-contact.routes.js";
import supplierDocumentRoutes from "../modules/supplier-document/supplier-document.routes.js";
import surveyTemplateRoutes from "../modules/survey-template/survey-template.routes.js";
import surveyTemplateQuestionRoutes from "../modules/survey-template-question/survey-template-question.routes.js";
import packageGroupRoutes from "../modules/package-group/package-group.routes.js";
import packagePriceListItemMapRoutes from "../modules/package-pricelist-item-map/package-pricelist-item-map.routes.js";
import taskRoutes from "../modules/task/task.routes.js";
import locationRoutes from "../modules/location/location.routes.js";
import estateRoutes from "../modules/estate/estate.routes.js";
import estateFeatureRoutes from "../modules/estate-feature/estate-feature.routes.js";
import estateStageRoutes from "../modules/estate-stage/estate-stage.routes.js";
import estateDocumentImageRoutes from "../modules/estate-document-image/estate-document-image.routes.js";
import constructionSettingRoutes from "../modules/construction-setting/construction-setting.routes.js";
import constructionOptionRoutes from "../modules/construction-option/construction-option.routes.js";
import quotationSettingRoutes from "../modules/quotation-setting/quotation-setting.routes.js";
import appointmentRoutes from "../modules/appointment/appointment.routes.js";
import holidayRoutes from "../modules/holiday/holiday.routes.js";
import recalculateDateRoutes from "../modules/recalculate-date/recalculate-date.routes.js";
import constructionTypeRoutes from "../modules/construction-type/construction-type.routes.js";
import constructionStageRoutes from "../modules/construction-stage/construction-stage-.routes.js";
import constructionChecklistRoutes from "../modules/construction-checklist/construction-checklist.routes.js";
import constructionSubChecklistRoutes from "../modules/construction-sub-checklist/construction-sub-checklist.routes.js";
import constructionChecklistPredecessorRoutes from "../modules/construction-checklist-predecessor/construction-checklist-predecessor.routes.js";
import constructionInspectionChecklistRoutes from "../modules/construction-inspection-checklist/construction-inspection-checklist.routes.js";
import constructionOHSRoutes from "../modules/construction-ohs/construction-ohs.routes.js";
import constructionEtsRechargeRoutes from "../modules/construction-ets-recharge/construction-ets-recharge.routes.js";
import constructionEtsRechargeApprovalRoutes from "../modules/construction-ets-recharge-approval/construction-ets-recharge-approval.routes.js";
import timezoneRoutes from "../modules/timezone/timezone.routes.js";
import roleTypeRoutes from "../modules/role-type/role-type.routes.js";
import costCenterRoutes from "../modules/cost-center/cost-center.routes.js";
import complianceTypeRoutes from "../modules/compliance-type/compliance-type.routes.js";
import driveRoutes from "../modules/drive/drive.routes.js";
import colorGrouprouts from "../modules/color-group/color-group.routes.js";
import colorGroupItemMapRoutes from "../modules/color-group-item-map/color-group-item-map.routes.js";
import contractFormatRoutes from "../modules/contract-format/contract-format.routes.js";
import contractSectionRoutes from "../modules/contract-section/contract-section.routes.js";
import quotationFormatMasterSectionRoutes from "../modules/quotation-format-master-section/quotation-format-master-section.routes.js";
import contactRoutes from "../modules/contact/contact.routes.js";
import lotRoutes from "../modules/lot/lot.routes.js";
import lotPackageGroupRoutes from "../modules/lot-package-group/lot-package-group.routes.js";
import lotPackageRoutes from "../modules/lot-package/lot-package.routes.js";
import houseFeatureRoutes from "../modules/house-feature/house-feature.routes.js";
import houseLandPackageRoutes from "../modules/house-land-package/house-land-package.routes.js";
import hLPackagePricelistItemCommissionRoutes from "../modules/h-l-package-pricelist-item-commission/h-l-package-pricelist-item-commission.routes.js";
import jobFormRoutes from "../modules/job-form/job-form.routes.js";
import businessContactRoutes from "../modules/business-contact/business-contact.routes.js";
import hlPackageLotPackageMapRoutes from "../modules/hl-package-lot-package-map/hl-package-lot-package-map.routes.js";
import quotationVersionCustomSectionRoutes from "../modules/quotation-version-custom-section/quotation-version-custom-section.routes.js";
import quotationVersionPackageMapRoutes from "../modules/quotation-version-package-map/quotation-version-package-map.routes.js";
import quotationVersionPricelistItemMapRoutes from "../modules/quotation-version-price-list/quotation-version-pricelist-item-map.routes.js";

export default function (app) {
  app.use("/country", countryRoutes);
  app.use("/state", stateRoutes);
  app.use("/auth", authRoutes);
  app.use("/user", userRoutes);
  app.use("/agent-referral-partner", agentReferralPartnerRoutes);
  app.use("/user-group", userGroupRoutes);
  app.use("/builder", builderRoutes);
  app.use("/contractor", contractorRoutes);
  app.use("/service", serviceRoutes);
  app.use("/sales/lead-source", leadSourceRoutes);
  app.use("/leads", leadRoutes);
  app.use("/leads-contact-map", leadsContactMapRoutes);
  app.use("/opportunities", opportunitiesRoutes);
  app.use("/master-price-category", masterPriceListCategoryRoutes);
  app.use("/range", rangeRoutes);
  app.use("/dwelling-type", dwellingTypeRoutes);
  app.use("/floor-plan", floorPlanRoutes);
  app.use("/floor-plan-pricelist-item-map", floorPlanPricelistItemMapRoutes);
  app.use("/floor-plan-facade-map", floorPlanFacadeMapRoutes);
  app.use("/facade", masterFacadeRoutes);
  app.use("/condition", conditionRoutes);
  app.use("/category-item", masterPriceListCategoryItemRoutes);
  app.use("/package", packageRoutes);
  app.use("/inclusion-package", inclusionPackageRoutes);
  app.use("/property", propertyRoutes);
  app.use("/dashboard", dashboardRoutes);
  app.use("/quotation", quotationRoutes);
  app.use("/job", jobRoutes);
  app.use("/actions", actionsRoutes);
  app.use("/tags", tagsRoutes);
  app.use("/workflow-process", workflowProcessRoutes);
  app.use("/color", colorRoutes);
  app.use("/color-category", colorCategoryRoutes);
  app.use("/color-sub-category", colorSubCategoryRoutes);
  app.use("/color-item", colorItemRoutes);
  app.use("/color-item-custom-field", colorItemCustomFieldRoutes);
  app.use("/color-group-item-map", colorGroupItemMapRoutes);
  app.use("/color-type", colorTypeRoutes);
  app.use("/workflow-process-task", workflowProcessTaskRoutes);
  app.use("/invoice", invoiceRoutes);
  app.use("/screen", screenRoutes);
  app.use("/address", addressRoutes);
  app.use("/company", companyRoutes);
  app.use("/functionality", functionalityRoutes);
  app.use("/checklist", checklistRoutes);
  app.use("/checklist-item", checklistItemRoutes);
  app.use("/general-setting", generalSettingRoutes);
  app.use("/surveyor", surveyorRoutes);
  app.use("/custom-field-module", customFieldModuleRoutes);
  app.use("/custom-field", customFieldRoutes);
  app.use("/custom-field-value", customFieldValueRoutes);
  app.use("/note-tag", noteTagRoutes);
  app.use("/role", roleRoutes);
  app.use("/role-permission", rolePermissionRoutes);
  app.use("/password-policy", passwordPolicyRoutes);
  app.use("/user-role-mapping", userRoleMappingRoutes);
  app.use("/user-password-history", userPasswordHistoryRoutes);
  app.use("/sales-module-setting", salesModuleSettingRoutes);
  app.use("/sales-proccess", salesProcessRoutes);
  app.use(
    "/sales-proccess-stage-functionality",
    salesProcessStageFunctionalityRoutes,
  );
  app.use("/sales-stage", salesStageRoutes);
  app.use("/lead-lost-reason", leadLostReasonRoutes);
  app.use("/client-type", clientTypeRoutes);
  app.use("/house-land-package-setting", houseLandPackageSettingRoutes);
  app.use("/job-setting", jobSettingRoutes);
  app.use("/job-color-setting", jobColorSettingRoutes);
  app.use("/job-color-column", jobColorColumnRoutes);
  app.use("/job-color-column-section", jobColorColumnSectionRoutes);
  app.use("/job-workflow-setting", jobWorkflowSettingRoutes);
  app.use("/job-invoice-setting", jobInvoiceSettingRoutes);
  app.use("/job-invoice-stage-payment", jobInvoiceStagePaymentRoutes);
  app.use("/job-variation-setting", jobVariationSettingRoutes);
  app.use("/job-commission-setting", jobCommissionsettingRoutes);
  app.use("/job-commission", jobCommissionRoutes);
  app.use("/job-commission-sub-stage", jobCommissionSubStageRoutes);
  app.use("/job-process", jobProcessRoutes);
  app.use(
    "/job-process-stage-functionality",
    jobProcessStageFunctionalityRoutes,
  );
  app.use("/job-variation-approval", jobVariationApprovalRoutes);
  app.use("/maintenance-setting", maintenanceSettingRoutes);
  app.use("/maintenance-area", maintenanceAreaRoutes);
  app.use("/document-common-folder", documentCommonFolderRoutes);
  app.use("/document-common-subfolder", documentCommonSubfolderRoutes);
  app.use("/document-file-naming-rule", documentFileNamingRuleRoutes);
  app.use("/document-folder-mapping", documentFolderMappingroutes);
  app.use("/integration-setting", integrationSettingRoutes);
  app.use(
    "/integration-custom-field-header",
    integrationCustomFieldHeaderRoutes,
  );
  app.use("/integration-custom-field-item", integrationCustomFieldItemRoutes);
  app.use("/template-email", templateEmailRoutes);
  app.use("/template-email-signature", templateEmailSignatureRoutes);
  app.use("/template-note", templateNoteRoutes);
  app.use("/template-pdf", templatePDFRoutes);
  app.use("/scheduler-email", schedulerEmailRoutes);
  app.use("/scheduler-setting", schedulerSettingRoutes);
  app.use("/portal-setting", portalSettingRoutes);
  app.use("/price-list", priceListRoutes);
  app.use("/price-list-item", priceListItemRoutes);
  app.use("/price-list-item-condition", priceListItemConditionRoutes);
  app.use("/supplier-type", supplierTypeRoutes);
  app.use("/supplier", supplierRoutes);
  app.use("/supplier-type-map", supplierTypeMapRoutes);
  app.use("/supplier-contact", supplierContactRoutes);
  app.use("/supplier-document", supplierDocumentRoutes);
  app.use("/survey-template", surveyTemplateRoutes);
  app.use("/survey-template-question", surveyTemplateQuestionRoutes);
  app.use("/package-group", packageGroupRoutes);
  app.use("/package-price-list-item-map", packagePriceListItemMapRoutes);
  app.use("/task", taskRoutes);
  app.use("/location", locationRoutes);
  app.use("/estate", estateRoutes);
  app.use("/estate-feature", estateFeatureRoutes);
  app.use("/estate-stage", estateStageRoutes);
  app.use("/estate-document-image", estateDocumentImageRoutes);
  app.use("/construction-setting", constructionSettingRoutes);
  app.use("/construction-option", constructionOptionRoutes);
  app.use("/quotation-setting", quotationSettingRoutes);
  app.use("/appointment", appointmentRoutes);
  app.use("/holiday", holidayRoutes);
  app.use("/recalculate-date", recalculateDateRoutes);
  app.use("/construction-type", constructionTypeRoutes);
  app.use("/construction-stage", constructionStageRoutes);
  app.use("/construction-checklist", constructionChecklistRoutes);
  app.use("/construction-sub-checklist", constructionSubChecklistRoutes);
  app.use(
    "/construction-checklist-predecessor",
    constructionChecklistPredecessorRoutes,
  );
  app.use("/construction-ohs", constructionOHSRoutes);
  app.use(
    "/construction-inspection-checklist",
    constructionInspectionChecklistRoutes,
  );
  app.use("/construction-ets-recharge", constructionEtsRechargeRoutes);
  app.use(
    "/construction-ets-recharge-approval",
    constructionEtsRechargeApprovalRoutes,
  );
  app.use("/timezone", timezoneRoutes);
  app.use("/role-type", roleTypeRoutes);
  app.use("/cost-center", costCenterRoutes);
  app.use("/compliance-type", complianceTypeRoutes);
  app.use("/drive", driveRoutes);
  app.use("/color-group", colorGrouprouts);
  app.use("/contract-format", contractFormatRoutes);
  app.use("/contract-section", contractSectionRoutes);
  app.use("/quotation-format", quotationFormatMasterSectionRoutes);
  app.use("/contact", contactRoutes);
  app.use("/lot", lotRoutes);
  app.use("/lot-package-group", lotPackageGroupRoutes);
  app.use("/lot-package", lotPackageRoutes);
  app.use("/house-feature", houseFeatureRoutes);
  app.use("/house-land-package", houseLandPackageRoutes);
  app.use("/hl-package-pricelist-item-commission", hLPackagePricelistItemCommissionRoutes);
  app.use("/job-form", jobFormRoutes);
  app.use("/business-contact", businessContactRoutes);
  app.use("/hl-package-lot-package-map", hlPackageLotPackageMapRoutes);
  app.use("/quotation-version-custom-section", quotationVersionCustomSectionRoutes);
  app.use("/quotation-version-pricelist-item-map", quotationVersionPricelistItemMapRoutes);
}
