const agentReferralPartnerRepo = require("./agent-referral-partner.repository");
const addressRepo = require("../../repositories/address.repository");//need to change path
const { keysToCamelCase } = require("../../utils/common");
const { encrypt } = require("../../utils/crypto.util");
const { generateStrongPassword } = require("../../utils/password.util");
const getPool = require("../../config/database");

const { sendPasswordEmail } = require("../../service/email.service");

async function createAgentReferralPartner(currentUser, body, client) {
  const {
    address,
    user,
    account_name,
    account_bsb,
    account_number,
    abn,
    company_name,
    referred_user_id,
  } = body;

  const {
    name,
    email,
    phone,
    create_login = false,
    login_id,
    password,
    password_auto_generated = false,
    manual_password,
    next_login_password_change = false,
    email_login_credentials = false,
  } = user || {};

  const existingPartner =
    await agentReferralPartnerRepo.getAgentReferralPartnerByEmail(
      email,
      client,
    );

  if (existingPartner) {
    throw {
      status: 409,
      message: "Agent referral partner with this email already exists.",
    };
  }

  if (email) {
    const existingUser = await client.query(
      "SELECT users_id FROM users WHERE email = $1",
      [email],
    );

    if (existingUser.rows.length > 0) {
      throw {
        status: 409,
        message: "Email already exists in the system.",
      };
    }
  }

  let finalLoginId = login_id;
  let finalPassword =
    password_auto_generated === false ? manual_password : password;
  let passwordAutoGenerated = password_auto_generated === true;
  let createdUserId = null;

  if (name && email && phone) {
    const roleResult = await client.query(
      "SELECT role_id FROM role WHERE name = $1",
      ["Agent"],
    );

    if (roleResult.rows.length === 0) {
      throw {
        status: 500,
        message: "Agent role not found in the system.",
      };
    }

    const agentRoleId = roleResult.rows[0].role_id;

    if (create_login) {
      if (!finalLoginId) {
        throw {
          status: 400,
          message: "Login ID is required when creating login credentials.",
        };
      }

      if (password_auto_generated === true || !finalPassword) {
        finalPassword = generateStrongPassword();
        passwordAutoGenerated = true;
      }

      const existingLogin = await client.query(
        "SELECT users_id FROM users WHERE login_id = $1",
        [finalLoginId],
      );

      if (existingLogin.rows.length > 0) {
        throw {
          status: 409,
          message:
            "Login ID already exists. Please choose a different login ID.",
        };
      }

      if (email_login_credentials || passwordAutoGenerated) {
        try {
          await sendPasswordEmail(email, finalLoginId, finalPassword);
        } catch (error) {}
      }

      finalPassword = encrypt(finalPassword);

      const userRes = await client.query(
        `
          INSERT INTO users (
            name, email, login_id, password, phone,
            builder_id, role_id, is_active, is_locked, is_verified,
            password_auto_generated, next_login_password_change, email_login_credentials, has_login
          ) VALUES (
            $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14
          ) RETURNING users_id
        `,
        [
          name,
          email,
          finalLoginId,
          finalPassword,
          phone,
          currentUser.builder_id || null,
          agentRoleId,
          true,
          false,
          true,
          passwordAutoGenerated,
          next_login_password_change,
          email_login_credentials,
          true, // has_login = true when create_login is true
        ],
      );
      createdUserId = userRes.rows[0].users_id;
    } else {
      // Create user without login credentials
      const userRes = await client.query(
        `
          INSERT INTO users (
            name, email, phone, builder_id, role_id, is_active, is_locked, is_verified, has_login, password, login_id
          ) VALUES (
            $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
          ) RETURNING users_id
        `,
        [
          name,
          email,
          phone,
          currentUser.builder_id || null,
          agentRoleId,
          true,
          false,
          true,
          false, // has_login = false initially
          "", // password = empty string when no login credentials
          null, // login_id = null when no login credentials
        ],
      );
      createdUserId = userRes.rows[0].users_id;
    }
  }

  let addressId = null;
  if (address) {
    addressId = await addressRepo.createOrUpdateAddress(null, address, client);
  }

  const partnerData = {
    company_id: currentUser.company_id || null,
    builder_id: currentUser.builder_id || null,
    user_id: createdUserId,
    address_id: addressId,
    account_name,
    account_bsb,
    account_number,
    abn,
    company_name,
    referred_user_id,
    created_by: currentUser.user_id || currentUser.users_id,
  };

  try {
    const partner = await agentReferralPartnerRepo.createAgentReferralPartner(
      partnerData,
      client,
    );
    return keysToCamelCase(partner);
  } catch (error) {
    throw error;
  }
}

async function getAgentReferralPartnerById(partnerId) {
  const partner =
    await agentReferralPartnerRepo.getAgentReferralPartnerById(partnerId);
  if (!partner) {
    throw { status: 404, message: "Agent referral partner not found." };
  }
  return keysToCamelCase(partner);
}

async function transformAgentReferralPartnerResponse(partner) {
  const transformed = keysToCamelCase(partner);

  // Fetch detailed user data if userId exists
  let userObject = {};
  if (partner.userId) {
    const pool = getPool();
    const client = await pool.connect();
    try {
      const userQuery = await client.query(
        `SELECT users_id, name, email, phone, login_id, password, 
                next_login_password_change, email_login_credentials, 
                password_auto_generated, is_active
         FROM users 
         WHERE users_id = $1 AND is_deleted = false`,
        [partner.userId],
      );

      if (userQuery.rowCount > 0) {
        const user = userQuery.rows[0];
        userObject = {
          userId: user.users_id,
          name: user.name,
          email: user.email,
          phone: user.phone,
          createLogin: user.password_auto_generated || false,
          loginId: user.login_id,
          passwordOption: user.password ? "manual" : null,
          manualPassword: user.password || null,
          nextLoginPasswordChange: user.next_login_password_change || false,
          emailLoginCredentials: user.email_login_credentials || false,
          isActive: user.is_active,
        };
      }
    } finally {
      client.release();
    }
  }

  // Fetch detailed address data if addressId exists (single object, not array)
  let addressObject = {};
  if (partner.addressId) {
    const pool = getPool();
    const client = await pool.connect();
    try {
      const addressQuery = await client.query(
        `SELECT address_id, address_line1, address_line2, city, state_id, country_id, zip_code 
             FROM address WHERE address_id = $1`,
        [partner.addressId],
      );

      if (addressQuery.rowCount > 0) {
        const address = addressQuery.rows[0];
        addressObject = {
          addressId: address.address_id,
          addressLine1: address.address_line1,
          addressLine2: address.address_line2,
          city: address.city,
          stateId: address.state_id,
          countryId: address.country_id,
          zipCode: address.zip_code,
        };
      }
    } finally {
      client.release();
    }
  }

  // Remove individual fields that are now in nested objects
  delete transformed.userId;
  delete transformed.addressId;

  // Build response with proper field order
  const response = {
    agentReferralPartnerId: transformed.agentReferralPartnerId,
    companyId: transformed.companyId,
    builderId: transformed.builderId,
    user: userObject,
    address: addressObject,
    companyName: transformed.companyName,
    accountName: transformed.accountName,
    accountBsb: transformed.accountBsb,
    accountNumber: transformed.accountNumber,
    abn: transformed.abn,
    referredUserId: transformed.referredUserId,
    createdBy: transformed.createdBy,
    updatedBy: transformed.updatedBy,
    createdAt: transformed.createdAt,
    updatedAt: transformed.updatedAt,
  };

  return response;
}

async function getAgentReferralPartners(currentUser, query) {
  let result;

  if (currentUser.company_id) {
    result = await agentReferralPartnerRepo.getAgentReferralPartnersByCompany(
      currentUser.company_id,
      query,
    );
  } else if (currentUser.builder_id) {
    result = await agentReferralPartnerRepo.getAgentReferralPartnersByBuilder(
      currentUser.builder_id,
      query,
    );
  } else {
    throw { status: 403, message: "User must belong to a company or builder." };
  }

  // Transform data to match required response structure
  const transformedData = await Promise.all(
    result.data.map(async (partner) => {
      const transformed = keysToCamelCase(partner);

      // Fetch detailed user data if user_id exists
      let userObject = null;
      if (partner.user_id) {
        const pool = getPool();
        const client = await pool.connect();
        try {
          const userQuery = await client.query(
            `SELECT users_id, name, email, phone, login_id, password, 
                    next_login_password_change, email_login_credentials, 
                    password_auto_generated, is_active, is_locked
             FROM users 
             WHERE users_id = $1 AND is_deleted = false`,
            [partner.user_id],
          );

          if (userQuery.rowCount > 0) {
            const user = userQuery.rows[0];
            userObject = {
              userId: user.users_id,
              name: user.name,
              email: user.email,
              phone: user.phone,
              createLogin: user.password_auto_generated || false,
              loginId: user.login_id,
              passwordOption: user.password ? "manual" : null,
              manualPassword: user.password || null,
              nextLoginPasswordChange: user.next_login_password_change || false,
              emailLoginCredentials: user.email_login_credentials || false,
              isActive: user.is_active,
              isLocked: user.is_locked || false,
            };
          }
        } finally {
          client.release();
        }
      }

      // Fetch detailed address data if address_id exists (single object, not array)
      let addressObject = null;
      if (partner.address_id) {
        const pool = getPool();
        const client = await pool.connect();
        try {
          const addressQuery = await client.query(
            `SELECT address_id, address_line1, address_line2, city, state_id, country_id, zip_code 
             FROM address WHERE address_id = $1`,
            [partner.address_id],
          );

          if (addressQuery.rowCount > 0) {
            const address = addressQuery.rows[0];
            addressObject = {
              addressId: address.address_id,
              addressLine1: address.address_line1,
              addressLine2: address.address_line2,
              city: address.city,
              stateId: address.state_id,
              countryId: address.country_id,
              zipCode: address.zip_code,
            };
          }
        } finally {
          client.release();
        }
      }

      // Remove individual fields that are now in nested objects
      delete transformed.userId;
      delete transformed.addressId;

      // Build response with proper field order
      const response = {
        agentReferralPartnerId: transformed.agentReferralPartnerId,
        companyId: transformed.companyId,
        builderId: transformed.builderId,
        user: userObject,
        address: addressObject,
        companyName: transformed.companyName,
        accountName: transformed.accountName,
        accountBsb: transformed.accountBsb,
        accountNumber: transformed.accountNumber,
        abn: transformed.abn,
        referredUserId: transformed.referredUserId,
        createdBy: transformed.createdBy,
        updatedBy: transformed.updatedBy,
        createdAt: transformed.createdAt,
        updatedAt: transformed.updatedAt,
      };

      return response;
    }),
  );

  return {
    ...result,
    data: transformedData,
  };
}

async function updateAgentReferralPartner(
  currentUser,
  partnerId,
  body,
  client,
) {
  const existingPartner =
    await agentReferralPartnerRepo.getAgentReferralPartnerById(
      partnerId,
      client,
    );

  if (!existingPartner) {
    throw { status: 404, message: "Agent referral partner not found." };
  }

  if (
    currentUser.company_id &&
    existingPartner.company_id !== currentUser.company_id
  ) {
    throw {
      status: 403,
      message: "You can only update partners from your own company.",
    };
  }
  if (
    currentUser.builder_id &&
    existingPartner.builder_id !== currentUser.builder_id
  ) {
    throw {
      status: 403,
      message: "You can only update partners from your own builder.",
    };
  }

  const {
    address,
    user,
    account_name,
    account_bsb,
    account_number,
    abn,
    company_name,
    referred_user_id,
  } = body;

  const {
    name,
    email,
    phone,
    create_login,
    login_id,
    password,
    password_auto_generated = false,
    manual_password,
    next_login_password_change,
    email_login_credentials,
    is_active,
  } = user || {};

  // Get existing user email if not provided in update
  let userEmail = email;
  if (!userEmail && existingPartner.user_id) {
    const userResult = await client.query(
      "SELECT email FROM users WHERE users_id = $1",
      [existingPartner.user_id],
    );
    if (userResult.rows.length > 0) {
      userEmail = userResult.rows[0].email;
    }
  }

  if (email && existingPartner.user_id) {
    const existingEmail = await client.query(
      `SELECT u.users_id, arp.agent_referral_partner_id 
       FROM users u 
       LEFT JOIN agent_referral_partner arp ON u.users_id = arp.user_id 
       WHERE u.email = $1 AND u.users_id != $2`,
      [email, existingPartner.user_id],
    );

    if (existingEmail.rows.length > 0) {
      throw {
        status: 409,
        message: "Email already exists in the system.",
      };
    }
  }

  let addressId = existingPartner.address_id;
  if (address) {
    addressId = await addressRepo.createOrUpdateAddress(
      existingPartner.address_id,
      address,
      client,
    );
  }

  let finalLoginId = login_id || existingPartner.login_id;
  let finalPassword =
    password_auto_generated === false
      ? manual_password
      : password || existingPartner.password;
  let passwordAutoGenerated = password_auto_generated === true;

  if (
    create_login !== undefined &&
    create_login !== existingPartner.create_login
  ) {
    if (create_login) {
      if (!finalLoginId) {
        throw {
          status: 400,
          message: "Login ID is required when creating login credentials.",
        };
      }

      const existingLogin = await client.query(
        "SELECT users_id FROM users WHERE login_id = $1 AND users_id != $2",
        [finalLoginId, existingPartner.user_id],
      );

      if (existingLogin.rows.length > 0) {
        throw {
          status: 409,
          message:
            "Login ID already exists. Please choose a different login ID.",
        };
      }

      if (password_auto_generated === true || !finalPassword) {
        finalPassword = generateStrongPassword();
        passwordAutoGenerated = true;
      }

      if (email_login_credentials || passwordAutoGenerated) {
        try {
          await sendPasswordEmail(userEmail, finalLoginId, finalPassword);
        } catch (error) {}
      }

      finalPassword = encrypt(finalPassword);
    } else {
      finalLoginId = null;
      finalPassword = null;
      passwordAutoGenerated = false;
    }
  } else if (
    create_login &&
    password_auto_generated === false &&
    manual_password
  ) {
    if (finalLoginId) {
      const existingLogin = await client.query(
        "SELECT users_id FROM users WHERE login_id = $1 AND users_id != $2",
        [finalLoginId, existingPartner.user_id],
      );

      if (existingLogin.rows.length > 0) {
        throw {
          status: 409,
          message:
            "Login ID already exists. Please choose a different login ID.",
        };
      }
    }

    if (email_login_credentials) {
      try {
        await sendPasswordEmail(userEmail, finalLoginId, manual_password);
      } catch (error) {}
    }

    finalPassword = encrypt(manual_password);
    passwordAutoGenerated = false;
  }

  if (create_login === false && existingPartner.user_id) {
    await client.query(
      "UPDATE users SET is_verified = false, is_active = false, login_id = null WHERE users_id = $1",
      [existingPartner.user_id],
    );
  }

  if (existingPartner.user_id) {
    const userUpdateData = {};

    // Only include fields that are provided
    if (name !== undefined) userUpdateData.name = name;
    if (email !== undefined) userUpdateData.email = email;
    if (phone !== undefined) userUpdateData.phone = phone;
    if (is_active !== undefined) userUpdateData.is_active = is_active;

    if (create_login !== undefined) {
      if (create_login) {
        const existingUser = await client.query(
          "SELECT role_id FROM users WHERE users_id = $1",
          [existingPartner.user_id],
        );

        if (!existingUser.rows[0]?.role_id) {
          const roleResult = await client.query(
            "SELECT role_id FROM role WHERE name = $1",
            ["Agent"],
          );

          if (roleResult.rows.length > 0) {
            userUpdateData.role_id = roleResult.rows[0].role_id;
          }
        }

        userUpdateData.login_id = finalLoginId;
        userUpdateData.password = finalPassword;
        userUpdateData.password_auto_generated = passwordAutoGenerated;
        userUpdateData.next_login_password_change = next_login_password_change;
        userUpdateData.is_verified = true;
        userUpdateData.has_login = true; // Set has_login to true when creating login
      } else {
        userUpdateData.login_id = null;
        userUpdateData.is_active = false;
        userUpdateData.is_verified = false;
        userUpdateData.has_login = false; // Set has_login to false when disabling login
      }
    } else if (finalLoginId && finalPassword) {
      userUpdateData.login_id = finalLoginId;
      userUpdateData.password = finalPassword;
      userUpdateData.password_auto_generated = passwordAutoGenerated;
      userUpdateData.next_login_password_change = next_login_password_change;
    }

    // Only update user if there's data to update
    if (Object.keys(userUpdateData).length > 0) {
      await client.query(
        `
          UPDATE users 
          SET ${Object.keys(userUpdateData)
            .map((key, index) => `${key} = $${index + 2}`)
            .join(", ")}, updated_at = NOW()
          WHERE users_id = $1
        `,
        [existingPartner.user_id, ...Object.values(userUpdateData)],
      );
    }
  }

  if (referred_user_id !== undefined && referred_user_id !== null) {
    const referredUser = await client.query(
      "SELECT users_id FROM users WHERE users_id = $1 AND is_deleted = false AND is_active = true",
      [referred_user_id],
    );

    if (referredUser.rowCount === 0) {
      throw {
        status: 400,
        message: "Referred user not found or is inactive.",
      };
    }
  }

  const updateData = {
    address_id: existingPartner.address_id,
    account_name: existingPartner.account_name,
    account_bsb: existingPartner.account_bsb,
    account_number: existingPartner.account_number,
    abn: existingPartner.abn,
    company_name: existingPartner.company_name,
    referred_user_id: existingPartner.referred_user_id,
    updated_by: currentUser.user_id || currentUser.users_id,
  };

  if (addressId !== undefined) {
    updateData.address_id = addressId;
  }
  if (account_name !== undefined) {
    updateData.account_name = account_name;
  }
  if (account_bsb !== undefined) {
    updateData.account_bsb = account_bsb;
  }
  if (account_number !== undefined) {
    updateData.account_number = account_number;
  }
  if (abn !== undefined) {
    updateData.abn = abn;
  }
  if (company_name !== undefined) {
    updateData.company_name = company_name;
  }
  if (referred_user_id !== undefined) {
    updateData.referred_user_id = referred_user_id;
  }

  const partner = await agentReferralPartnerRepo.updateAgentReferralPartner(
    partnerId,
    updateData,
    client,
  );
  return keysToCamelCase(partner);
}

async function deleteAgentReferralPartner(currentUser, partnerId, client) {
  const existingPartner =
    await agentReferralPartnerRepo.getAgentReferralPartnerById(
      partnerId,
      client,
    );
  if (!existingPartner) {
    throw { status: 404, message: "Agent referral partner not found." };
  }

  if (
    currentUser.company_id &&
    existingPartner.company_id !== currentUser.company_id
  ) {
    throw {
      status: 403,
      message: "You can only delete partners from your own company.",
    };
  }
  if (
    currentUser.builder_id &&
    existingPartner.builder_id !== currentUser.builder_id
  ) {
    throw {
      status: 403,
      message: "You can only delete partners from your own builder.",
    };
  }

  const partner = await agentReferralPartnerRepo.deleteAgentReferralPartner(
    partnerId,
    client,
  );
  return keysToCamelCase(partner);
}

module.exports = {
  createAgentReferralPartner,
  getAgentReferralPartnerById,
  getAgentReferralPartners,
  updateAgentReferralPartner,
  deleteAgentReferralPartner,
  transformAgentReferralPartnerResponse,
};
