import agentReferralPartnerRepo from "./agent-referral-partner.repository.js";
import addressRepo from "../../repositories/address.repository.js";
import { keysToCamelCase } from "../../utils/common.js";
import { encrypt } from "../../utils/crypto.util.js";
import { generateStrongPassword } from "../../utils/password.util.js";
import { sendPasswordEmail } from "../../helper/sendEmail.js";

import { Op } from "sequelize";
import db from "../../config/database/models/postgre-models/index.js";

export async function createAgentReferralPartner(currentUser, body) {
  const { Users, Role } = db;

  const {
    address,
    user,
    account_name,
    account_bsb,
    account_number,
    abn,
    company_name,
    referred_user_id,
  } = body;

  const {
    name,
    email,
    phone,
    create_login = false,
    login_id,
    password,
    password_auto_generated = false,
    manual_password,
    next_login_password_change = false,
    email_login_credentials = false,
  } = user || {};

  const existingPartner =
    await agentReferralPartnerRepo.getAgentReferralPartnerByEmail(email);

  if (existingPartner) {
    throw { status: 409, message: "Agent referral partner with this email already exists." };
  }

  if (email) {
    const existingUser = await Users.findOne({
      attributes: ["users_id"],
      where: { email },
    });

    if (existingUser) {
      throw { status: 409, message: "Email already exists in the system." };
    }
  }

  const finalLoginId = login_id;
  let finalPassword = password_auto_generated === false ? manual_password : password;
  let passwordAutoGenerated = password_auto_generated === true;
  let createdUserId = null;

  if (name && email && phone) {
    const agentRole = await Role.findOne({
      attributes: ["role_id"],
      where: { name: "Agent" },
    });

    if (!agentRole) {
      throw { status: 500, message: "Agent role not found in the system." };
    }

    const agentRoleId = agentRole.role_id;

    if (create_login) {
      if (!finalLoginId) {
        throw { status: 400, message: "Login ID is required when creating login credentials." };
      }

      if (password_auto_generated === true || !finalPassword) {
        finalPassword = generateStrongPassword();
        passwordAutoGenerated = true;
      }

      const existingLogin = await Users.findOne({
        attributes: ["users_id"],
        where: { login_id: finalLoginId },
      });

      if (existingLogin) {
        throw { status: 409, message: "Login ID already exists. Please choose a different login ID." };
      }

      if (email_login_credentials || passwordAutoGenerated) {
        try {
          await sendPasswordEmail(email, finalLoginId, finalPassword);
        } catch (error) { }
      }

      finalPassword = encrypt(finalPassword);

      const createdUser = await Users.create({
        name,
        email,
        login_id: finalLoginId,
        password: finalPassword,
        phone,
        builder_id: currentUser.builder_id || null,
        role_id: agentRoleId,
        is_active: true,
        is_locked: false,
        is_verified: true,
        password_auto_generated: passwordAutoGenerated,
        next_login_password_change,
        email_login_credentials,
        has_login: true,
      });

      createdUserId = createdUser.users_id;
    } else {
      // Create user without login credentials
      const createdUser = await Users.create({
        name,
        email,
        phone,
        builder_id: currentUser.builder_id || null,
        role_id: agentRoleId,
        is_active: true,
        is_locked: false,
        is_verified: true,
        has_login: false,
        password: "",
        login_id: null,
      });

      createdUserId = createdUser.users_id;
    }
  }

  let addressId = null;
  if (address) {
    addressId = await addressRepo.createOrUpdateAddress(null, address);
  }

  const partnerData = {
    company_id: currentUser.company_id || null,
    builder_id: currentUser.builder_id || null,
    user_id: createdUserId,
    address_id: addressId,
    account_name,
    account_bsb,
    account_number,
    abn,
    company_name,
    referred_user_id,
    created_by: currentUser.user_id || currentUser.users_id,
  };

  try {
    const partner = await agentReferralPartnerRepo.createAgentReferralPartner(partnerData);
    return keysToCamelCase(partner);
  } catch (error) {
    throw error;
  }
}

export async function getAgentReferralPartnerById(partnerId) {
  const partner = await agentReferralPartnerRepo.getAgentReferralPartnerById(partnerId);
  if (!partner) {
    throw { status: 404, message: "Agent referral partner not found." };
  }
  return keysToCamelCase(partner);
}

export async function transformAgentReferralPartnerResponse(partner) {
  const { Users, Address } = db;
  const transformed = keysToCamelCase(partner);

  let userObject = {};
  if (partner.userId) {
    const user = await Users.findOne({
      attributes: [
        "users_id", "name", "email", "phone", "login_id", "password",
        "next_login_password_change", "email_login_credentials",
        "password_auto_generated", "is_active",
      ],
      where: {
        users_id: partner.userId,
        is_deleted: false,
      },
    });

    if (user) {
      userObject = {
        userId: user.users_id,
        name: user.name,
        email: user.email,
        phone: user.phone,
        createLogin: user.password_auto_generated || false,
        loginId: user.login_id,
        passwordOption: user.password ? "manual" : null,
        manualPassword: user.password || null,
        nextLoginPasswordChange: user.next_login_password_change || false,
        emailLoginCredentials: user.email_login_credentials || false,
        isActive: user.is_active,
      };
    }
  }

  let addressObject = {};
  if (partner.addressId) {
    const address = await Address.findOne({
      attributes: ["address_id", "address_line1", "address_line2", "city", "state_id", "country_id", "zip_code"],
      where: { address_id: partner.addressId },
    });

    if (address) {
      addressObject = {
        addressId: address.address_id,
        addressLine1: address.address_line1,
        addressLine2: address.address_line2,
        city: address.city,
        stateId: address.state_id,
        countryId: address.country_id,
        zipCode: address.zip_code,
      };
    }
  }

  delete transformed.userId;
  delete transformed.addressId;

  return {
    agentReferralPartnerId: transformed.agentReferralPartnerId,
    companyId: transformed.companyId,
    builderId: transformed.builderId,
    user: userObject,
    address: addressObject,
    companyName: transformed.companyName,
    accountName: transformed.accountName,
    accountBsb: transformed.accountBsb,
    accountNumber: transformed.accountNumber,
    abn: transformed.abn,
    referredUserId: transformed.referredUserId,
    createdBy: transformed.createdBy,
    updatedBy: transformed.updatedBy,
    createdAt: transformed.createdAt,
    updatedAt: transformed.updatedAt,
  };
}

export async function getAgentReferralPartners(currentUser, query) {
  const { Users, Address } = db;

  let result;
  if (currentUser.company_id) {
    result = await agentReferralPartnerRepo.getAgentReferralPartnersByCompany(
      currentUser.company_id,
      query,
    );
  } else if (currentUser.builder_id) {
    result = await agentReferralPartnerRepo.getAgentReferralPartnersByBuilder(
      currentUser.builder_id,
      query,
    );
  } else {
    throw { status: 403, message: "User must belong to a company or builder." };
  }

  const transformedData = await Promise.all(
    result.data.map(async (partner) => {
      const transformed = keysToCamelCase(partner);

      let userObject = null;
      if (partner.user_id) {
        const user = await Users.findOne({
          attributes: [
            "users_id", "name", "email", "phone", "login_id", "password",
            "next_login_password_change", "email_login_credentials",
            "password_auto_generated", "is_active", "is_locked",
          ],
          where: {
            users_id: partner.user_id,
            is_deleted: false,
          },
        });

        if (user) {
          userObject = {
            userId: user.users_id,
            name: user.name,
            email: user.email,
            phone: user.phone,
            createLogin: user.password_auto_generated || false,
            loginId: user.login_id,
            passwordOption: user.password ? "manual" : null,
            manualPassword: user.password || null,
            nextLoginPasswordChange: user.next_login_password_change || false,
            emailLoginCredentials: user.email_login_credentials || false,
            isActive: user.is_active,
            isLocked: user.is_locked || false,
          };
        }
      }

      let addressObject = null;
      if (partner.address_id) {
        const address = await Address.findOne({
          attributes: ["address_id", "address_line1", "address_line2", "city", "state_id", "country_id", "zip_code"],
          where: { address_id: partner.address_id },
        });

        if (address) {
          addressObject = {
            addressId: address.address_id,
            addressLine1: address.address_line1,
            addressLine2: address.address_line2,
            city: address.city,
            stateId: address.state_id,
            countryId: address.country_id,
            zipCode: address.zip_code,
          };
        }
      }

      delete transformed.userId;
      delete transformed.addressId;

      return {
        agentReferralPartnerId: transformed.agentReferralPartnerId,
        companyId: transformed.companyId,
        builderId: transformed.builderId,
        user: userObject,
        address: addressObject,
        companyName: transformed.companyName,
        accountName: transformed.accountName,
        accountBsb: transformed.accountBsb,
        accountNumber: transformed.accountNumber,
        abn: transformed.abn,
        referredUserId: transformed.referredUserId,
        createdBy: transformed.createdBy,
        updatedBy: transformed.updatedBy,
        createdAt: transformed.createdAt,
        updatedAt: transformed.updatedAt,
      };
    }),
  );

  return { ...result, data: transformedData };
}

export async function updateAgentReferralPartner(currentUser, partnerId, body) {
  const { Users, Role } = db;

  const existingPartner = await agentReferralPartnerRepo.getAgentReferralPartnerById(partnerId);

  if (!existingPartner) {
    throw { status: 404, message: "Agent referral partner not found." };
  }

  if (currentUser.company_id && existingPartner.company_id !== currentUser.company_id) {
    throw { status: 403, message: "You can only update partners from your own company." };
  }
  if (currentUser.builder_id && existingPartner.builder_id !== currentUser.builder_id) {
    throw { status: 403, message: "You can only update partners from your own builder." };
  }

  const {
    address, user, account_name, account_bsb, account_number,
    abn, company_name, referred_user_id,
  } = body;

  const {
    name, email, phone, create_login, login_id, password,
    password_auto_generated = false, manual_password,
    next_login_password_change, email_login_credentials, is_active,
  } = user || {};

  // Get existing user email if not provided
  let userEmail = email;
  if (!userEmail && existingPartner.user_id) {
    const existingUser = await Users.findOne({
      attributes: ["email"],
      where: { users_id: existingPartner.user_id },
    });
    if (existingUser) {
      userEmail = existingUser.email;
    }
  }

  if (email && existingPartner.user_id) {
    const existingEmail = await Users.findOne({
      attributes: ["users_id"],
      where: {
        email,
        users_id: { [Op.ne]: existingPartner.user_id },
      },
    });

    if (existingEmail) {
      throw { status: 409, message: "Email already exists in the system." };
    }
  }

  let addressId = existingPartner.address_id;
  if (address) {
    addressId = await addressRepo.createOrUpdateAddress(existingPartner.address_id, address);
  }

  let finalLoginId = login_id || existingPartner.login_id;
  let finalPassword = password_auto_generated === false
    ? manual_password
    : password || existingPartner.password;
  let passwordAutoGenerated = password_auto_generated === true;

  if (create_login !== undefined && create_login !== existingPartner.create_login) {
    if (create_login) {
      if (!finalLoginId) {
        throw { status: 400, message: "Login ID is required when creating login credentials." };
      }

      const existingLogin = await Users.findOne({
        attributes: ["users_id"],
        where: {
          login_id: finalLoginId,
          users_id: { [Op.ne]: existingPartner.user_id },
        },
      });

      if (existingLogin) {
        throw { status: 409, message: "Login ID already exists. Please choose a different login ID." };
      }

      if (password_auto_generated === true || !finalPassword) {
        finalPassword = generateStrongPassword();
        passwordAutoGenerated = true;
      }

      if (email_login_credentials || passwordAutoGenerated) {
        try {
          await sendPasswordEmail(userEmail, finalLoginId, finalPassword);
        } catch (error) { }
      }

      finalPassword = encrypt(finalPassword);
    } else {
      finalLoginId = null;
      finalPassword = null;
      passwordAutoGenerated = false;
    }
  } else if (create_login && password_auto_generated === false && manual_password) {
    if (finalLoginId) {
      const existingLogin = await Users.findOne({
        attributes: ["users_id"],
        where: {
          login_id: finalLoginId,
          users_id: { [Op.ne]: existingPartner.user_id },
        },
      });

      if (existingLogin) {
        throw { status: 409, message: "Login ID already exists. Please choose a different login ID." };
      }
    }

    if (email_login_credentials) {
      try {
        await sendPasswordEmail(userEmail, finalLoginId, manual_password);
      } catch (error) {
      }
    }

    finalPassword = encrypt(manual_password);
    passwordAutoGenerated = false;
  }

  if (create_login === false && existingPartner.user_id) {
    await Users.update(
      { is_verified: false, is_active: false, login_id: null },
      { where: { users_id: existingPartner.user_id } },
    );
  }

  if (existingPartner.user_id) {
    const userUpdateData = {};

    if (name !== undefined) {
      userUpdateData.name = name;
    }
    if (email !== undefined) {
      userUpdateData.email = email;
    }
    if (phone !== undefined) {
      userUpdateData.phone = phone;
    }
    if (is_active !== undefined) {
      userUpdateData.is_active = is_active;
    }

    if (create_login !== undefined) {
      if (create_login) {
        const existingUser = await Users.findOne({
          attributes: ["role_id"],
          where: { users_id: existingPartner.user_id },
        });

        if (!existingUser?.role_id) {
          const agentRole = await Role.findOne({
            attributes: ["role_id"],
            where: { name: "Agent" },
          });
          if (agentRole) {
            userUpdateData.role_id = agentRole.role_id;
          }
        }

        userUpdateData.login_id = finalLoginId;
        userUpdateData.password = finalPassword;
        userUpdateData.password_auto_generated = passwordAutoGenerated;
        userUpdateData.next_login_password_change = next_login_password_change;
        userUpdateData.is_verified = true;
        userUpdateData.has_login = true;
      } else {
        userUpdateData.login_id = null;
        userUpdateData.is_active = false;
        userUpdateData.is_verified = false;
        userUpdateData.has_login = false;
      }
    } else if (finalLoginId && finalPassword) {
      userUpdateData.login_id = finalLoginId;
      userUpdateData.password = finalPassword;
      userUpdateData.password_auto_generated = passwordAutoGenerated;
      userUpdateData.next_login_password_change = next_login_password_change;
    }

    if (Object.keys(userUpdateData).length > 0) {
      await Users.update(userUpdateData, {
        where: { users_id: existingPartner.user_id },
      });
    }
  }

  if (referred_user_id !== undefined && referred_user_id !== null) {
    const referredUser = await Users.findOne({
      attributes: ["users_id"],
      where: {
        users_id: referred_user_id,
        is_deleted: false,
        is_active: true,
      },
    });

    if (!referredUser) {
      throw { status: 400, message: "Referred user not found or is inactive." };
    }
  }

  const updateData = {
    address_id: addressId,
    account_name: account_name !== undefined ? account_name : existingPartner.account_name,
    account_bsb: account_bsb !== undefined ? account_bsb : existingPartner.account_bsb,
    account_number: account_number !== undefined ? account_number : existingPartner.account_number,
    abn: abn !== undefined ? abn : existingPartner.abn,
    company_name: company_name !== undefined ? company_name : existingPartner.company_name,
    referred_user_id: referred_user_id !== undefined ? referred_user_id : existingPartner.referred_user_id,
    updated_by: currentUser.user_id || currentUser.users_id,
  };

  const partner = await agentReferralPartnerRepo.updateAgentReferralPartner(partnerId, updateData);
  return keysToCamelCase(partner);
}

export async function deleteAgentReferralPartner(currentUser, partnerId) {
  const existingPartner = await agentReferralPartnerRepo.getAgentReferralPartnerById(partnerId);

  if (!existingPartner) {
    throw { status: 404, message: "Agent referral partner not found." };
  }

  if (currentUser.company_id && existingPartner.company_id !== currentUser.company_id) {
    throw { status: 403, message: "You can only delete partners from your own company." };
  }
  if (currentUser.builder_id && existingPartner.builder_id !== currentUser.builder_id) {
    throw { status: 403, message: "You can only delete partners from your own builder." };
  }

  const partner = await agentReferralPartnerRepo.deleteAgentReferralPartner(partnerId);
  return keysToCamelCase(partner);
}

export default {
  createAgentReferralPartner,
  getAgentReferralPartnerById,
  getAgentReferralPartners,
  updateAgentReferralPartner,
  deleteAgentReferralPartner,
  transformAgentReferralPartnerResponse,
};
