name: Deploy Node.js App to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'

    - name: Install dependencies
      run: npm install
      
    # - name: Build app
    #   run: npm run build

    - name: Clean old app folder on EC2
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: 52.66.68.116
        username: ubuntu
        key: ${{ secrets.EC2_PRIVATE_KEY }}
        script: |
          [ -d ~/app ] && rm -rf ~/app
          mkdir -p ~/app

    - name: Copy source code to EC2
      uses: appleboy/scp-action@v0.1.7
      with:
        host: 52.66.68.116
        username: ubuntu
        key: ${{ secrets.EC2_PRIVATE_KEY }}
        source: "src,server.js,package.json,package-lock.json"
        target: "~/app"

    - name: Create .env on EC2
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: 52.66.68.116
        username: ubuntu
        key: ${{ secrets.EC2_PRIVATE_KEY }}
        script: |
          cd ~/app
          cat > .env << EOF
          PORT=5000
          DATABASE_URL=
          JWT_SECRET=
          JWT_REFRESH_SECRET=
          JWT_SECRET_EXPIRATION=
          JWT_REFRESH_SECRET_EXPIRATION=
          GMAIL=
          PASSWORD=
          FRONTED_BASE_URL=
          BACKEND_URL=
          AWS_ACCESS_KEY_ID=
          AWS_SECRET_ACCESS_KEY=
          AWS_REGION=
          S3_BUCKET_NAME=
          EOF

    - name: Install and restart app on EC2
      uses: appleboy/ssh-action@v0.1.3
      with:
        host: 52.66.68.116
        username: ubuntu
        key: ${{ secrets.EC2_PRIVATE_KEY }}
        script: |
          cd ~/app
          npm install
          pm2 restart node-app || pm2 start npm --name "node-app" -- start
          pm2 save
